name: gendoc

on:
  push:
    branches:
      - develop

jobs:
  gendoc:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Print Go version
        run: go version

      - name: Install Build Essential
        run: sudo apt update && sudo apt install build-essential -y

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run gendoc
        working-directory: tools/gendoc
        run: go run main.go

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(gendoc): update docs"
          commit-message: "chore(gendoc): update docs"
          branch: chore/gendoc
          base: develop